### PR TITLE
LPS-85972 As a consumer developer I can use the ANY operator in the queries to filter structured content based on array/collection properties

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/26. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/89fe06a5fb37~1...89fe06a5fb37) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
