### PR TITLE
LPS-111469 Anonymous user multicompany support

### PR DESCRIPTION
**Pull request by darquesdev**
This is part of this epic https://issues.liferay.com/browse/LPS-111334

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
Jeu @darquesdev !!

I have forwarded the pull, but I think that would be awesome to add tests to IndividualSegmentsMessageListener.

Thanks!

**Comment by darquesdev** [comment]
Thanks @cgoncas !

Agreed, I've created a tech-task for that https://issues.liferay.com/browse/LPS-116680

**Pull request closed without merging**
