### PR TITLE
LPS-97283 - add to trashedModels the updated entry

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
We were not sending the updated entry to the array of trashed models.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @AliciaGarciaGarcia ,

Is it possible to add a test for this change?

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
@cgoncas I made test, maybe you can review it and tell me improvements about them

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See https://github.com/aliciagarciagarcia/liferay-portal/pull/10.

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
