### PR TITLE
LPS-114284 Add Search Container for Content Dashboard

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Separate the two first commits here https://github.com/brianchandotcom/liferay-portal/pull/89201

**Comment by dgarciasarai** [comment]
Two first commits here: https://github.com/dgarciasarai/liferay-portal/pull/239

**Pull request closed without merging**
