### PR TITLE
LPS-89658

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/67733

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67753. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/9a1e09359f92~3...9a1e09359f92) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67756. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/a62ca3ca8f5e~3...a62ca3ca8f5e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67758. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/f967dbf5de20~4...f967dbf5de20) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
