### PR TITLE
LPS-96399 - SF

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74758. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
