### PR TITLE
LPS-114696 Expose companyId in AsahFaroBackendClient

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/155. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/7d502eb82dcc~2...7d502eb82dcc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
