### PR TITLE
LPS-83841 Add Test for Structured Content

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
First part sent here: https://github.com/ahdezma/liferay-portal/pull/28

**Comment by juliocamarero** [comment]
Second part is here: https://github.com/juliocamarero/liferay-portal/pull/4357

**Pull request closed without merging**
