### PR TITLE
LPS-110727 DXP - Include search keywords for organic & paid traffic sources

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/486. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/151. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/8ca889e6c1ee~2...8ca889e6c1ee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
