### PR TITLE
LPS-107263 Only apply defaultLanguageField fallback when is enabled

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:seo

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83586. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
