### PR TITLE
LPS-116130 Add columns to search container

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/546. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/547. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
