### PR TITLE
LPS-55475 Add companyId to all tables

### PR DESCRIPTION
**Pull request by mdelapenya**
Please see RatingsStats method on UpgradeSharding

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/149. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/150. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/496. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/497. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/499. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/151. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/503. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/504. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
