### PR TITLE
LPS-110727 DXP - Include search keywords for organic & paid traffic sources

### PR DESCRIPTION
**Pull request by darquesdev**
@dgarciasarai

### CODE REVIEW

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/484. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/98f675fd8bb9~1...98f675fd8bb9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/150. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/a0d7ccfa89c7~1...a0d7ccfa89c7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
