### PR TITLE
LPS-65882-c

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-65882
Hi @cgoncas , I broke up the commits you made in [alee8888#198](https://github.com/alee8888/liferay-portal/pull/198) to try and apply just the visual changes you made to the setup wizard (see screenshot/.mp4 in the LPS ticket). If this is not appropriate or you don't have enough time to review before release (I know you're busy), then you can just close this pull. Thanks! @alee8888

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by cgoncas** [comment]
I think it is too risky to change the Setup Wizard just now, that we are waiting to release DXP (as I talked with @alee8888). After that, PM and UX should talk and decide how the Setup Wizard should work.

**Comment by jpince** [comment]
Sounds good, thanks!

**Pull request closed without merging**
