### PR TITLE
LPS-85301 Expose dataType of the value in the StructuredContent API

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Great @ruben-pulido . Please could you resend this pull with the commits:

- LPS-85301 Expose field data type
- LPS-85301 Support passing file when reading structure
- LPS-85301 Refactor: Rename _getDDMStructureWithNestedField to _getDDM…  …
- LPS-85301 Add all the fields
- LPS-85301 All the tests

Maybe we should rename test-journal-structured-nested-fields.json as test-journal-structured-all-fields.json.

You can resent it directly to brian :)

**Comment by ruben-pulido** [comment]
Review incorporarated and PR sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/64520

**Pull request closed without merging**
