### PR TITLE
LPS-86324 testDefaultTitleIsDisplayedWhenLocaleESRequestedIsNotAvailable

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:reopen

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Review comments incorporated into https://github.com/cgoncas/liferay-portal/pull/282

**Pull request closed without merging**
