### PR TITLE
LPS-55433 Work in progress

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi @cgoncas, I need your help on this :)

I did what we discussed yesterday but I got the following error

`com.liferay.document.library.events.DLFileVersionTest cannot be found by com.liferay.document.library.test_1.0.0
    [junit] java.lang.ClassNotFoundException: com.liferay.document.library.events.DLFileVersionTest cannot be found by com.liferay.document.library.test_1.0.0`

Could you point me what am I missing? This is still a work in progress, so could you resend back to me with your changes?

Thanks a lot for your help!

### CODE REVIEW

**Comment by marcellustavares** [comment]
Hi @cgoncas, did you have a chance to look at this?

Thanks

**Comment by cgoncas** [comment]
Sorry @marcellustavares , 

I had a problem with github and I didn't know nothing about this pull :(. I will check it out now. 

I am so Sorry!!!!!!

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
I should thank you for all your help @cgoncas :)

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/485. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/125. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
