### PR TITLE
LPS-86381 Create client tests verifying localized values in nested fields are returned if Accept-Language header is passed (after 1st review)

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/285. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/79a0fd7dc559~1...79a0fd7dc559) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/286

**Pull request closed without merging**
