### PR TITLE
LPS-108633 baseline

### PR DESCRIPTION
**Pull request by csierra**
/cc @adolfopa @martamedio

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:close

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by csierra** [comment]
vaya desastre no?

**Comment by csierra** [comment]
please see https://github.com/cgoncas/liferay-portal/pull/439

**Pull request closed without merging**
