### PR TITLE
LPS-85440

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63649

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63713. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/20afb8d4df24~1...20afb8d4df24) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63714. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/e5f26cef5027~3...e5f26cef5027) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
