### PR TITLE
LPS-85735 Use a site created specifically for tests instead of Liferay site

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63785. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/29a71e7646ad~1...29a71e7646ad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63786. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/8394a49e3506~1...8394a49e3506) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63788. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/bf7c5348ddcb~1...bf7c5348ddcb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
