### PR TITLE
LPS-54269

### PR DESCRIPTION
**Pull request by Preston-Crary**
Thanks for your help refactoring the test.  Especially 57c57a168810cc5d3f5f537531ad1542c5ea0af8 as it lead to the discovery of 1f57f357492135ffcd34a9e214c514b5b074f56e.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/migue/liferay-portal/pull/464. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
