### PR TITLE
LPS-105366 tests for new behaviour with the image alt metatag

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:seo

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82282. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/11a54e489436~5...11a54e489436) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
