### PR TITLE
LPS-64334 Merge SO and core Activities portlets

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37816. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37889. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38040. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
