### PR TITLE
LPS-85232 Integration test filtering StructuredContent by any keyword with eq operator

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Everything is ok in upstream, so you can send it to brian.

**Comment by ruben-pulido** [comment]
Thanks @cgoncas! Sent to Brian [here](https://github.com/brianchandotcom/liferay-portal/pull/65461)

**Pull request closed without merging**
