### PR TITLE
LPS-86324 Client tests for localized title in Structured Content

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64090. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
