### PR TITLE
LPS-88253 Simplify tests

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
Tests are now much easier to read! Great job @cgoncas! 👏

**Comment by ruben-pulido** [comment]
We can rename ContetSpaceApioTest to Conte**n**tSpaceApioTest

**Comment by cgoncas** [comment]
sent: https://github.com/brianchandotcom/liferay-portal/pull/65691

**Pull request closed without merging**
