### PR TITLE
LPS-103619 Rewrite macro to accommodate change in UX

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
Hey @cgoncas there was one more small issue detected: the **Sites** breadcrumb should be capitalized in the Item Selector. I changed our test to accommodate this [here](https://github.com/cgoncas/liferay-portal/pull/423/commits/17f62f57f67e765f600ba4a6e4e56209a1e957cb#diff-fc1c7403c5f5a4953db8d15ea886d63cR102) so it will fail for now until you change the code. If you don't think this is necessary you can change "Sites" back to lowercase. Thanks!

**Comment by austinchiang** [comment]
sites

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80807. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/6fe8f4f816cb~3...6fe8f4f816cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80810. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/4fa90c8ec9f7~4...4fa90c8ec9f7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
