### PR TITLE
LPS-115076 Filter by statuses DRAFT, APPROVED & SCHEDULED

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/161. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
