### PR TITLE
LPS-115915 Only the creator can see their drafts contents.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
c:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
See https://github.com/cgoncas/liferay-portal/pull/536

**Pull request closed without merging**
