### PR TITLE
LPS-86425 Expose label of the value in the StructuredContent API and verify it is localized

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64395. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64403. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/6ad77c9cc80b~1...6ad77c9cc80b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
