### PR TITLE
LPS-97535 Use the right type parameter for ModelIndexerWriterContributor in DLFileEntrySearchRegistrar

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-97535

Cheers,
Tibor :beach_umbrella: :wink:

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75110. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
