### PR TITLE
Lps 54421

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Master is broken on portal's jsp compile. Can you check what is breaking? Should be easy to fix.

If you have left for lunch too, we can look into it in the afternoon.

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25716. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/108. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25786. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
