### PR TITLE
LPS-98451 Tests for OAuth2StateUtil

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76563. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/81c37a6d6869~7...81c37a6d6869) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76564. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/2b998f1f1942~7...2b998f1f1942) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76571. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/7955ca71e299~8...7955ca71e299) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
