### PR TITLE
LPS-82637

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70019. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/dc99dad87913~1...dc99dad87913) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
