### PR TITLE
LPS-116011 Provide vocabulary metrics to UI

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/175. [See changes here.](https://github.com/cgoncas/liferay-portal/compare/ea277737d18a~2...ea277737d18a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
